### PR TITLE
ADD argNorm preprint to papers and news

### PR DESCRIPTION
**Pull request by Vedanth-Ramji**

### CODE REVIEW

**Comment by luispedro** [comment]
Add it as a paper as well

https://github.com/BigDataBiology/big-data-biology_org/tree/main/papers

**Comment by Vedanth-Ramji** [comment]
Done!

**Comment by luispedro** [comment]
> Binary file added (+62.9 MB)

Can you do it smaller? Much smaller (100x smaller)

**Comment by luispedro** [comment]
I merged everything but the last commit.

Instead of a separate function (`showcofirstauthorpaper`), I think it would be better to have a single function that takes a list of authors and behaves like the older function if it's one author and like your version of `showcofirstauthorpaper` if more (fine to even just support 1 or 2 authors for now)

**Pull request closed without merging**
