### PR TITLE
Add SemiBin tutorial

### PR DESCRIPTION
**Pull request by psj1997**

### CODE REVIEW

**Comment by luispedro** [comment]
ping @psj1997 : can you answer the comment above?

**Comment by psj1997** [comment]
Sorry, what comment you mean?

**Comment by luispedro** [comment]
The one about the installation. The review on the pull request

**Comment by psj1997** [comment]
Sorry, I do not see the review.

**Comment by luispedro** [comment]
You don't see this above?

image

**Comment by psj1997** [comment]
I do not know why I do not see this. But I will fix this.

**Pull request merged**
